name: Node with Express
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependecies
        run:  | 
            npm install
            npm ci
      - name: Run tests
        run: npm test
